-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 13:48:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rpacourse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rpacourse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rpacourse` DEFAULT CHARACTER SET utf8 ;
USE `rpacourse` ;

-- -----------------------------------------------------
-- Table `rpacourse`.`InvoiceStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpacourse`.`InvoiceStatus` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpacourse`.`InvoiceHeader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpacourse`.`InvoiceHeader` (
  `invoicenumber` INT NOT NULL,
  `companyname` VARCHAR(100) NULL,
  `companycode` VARCHAR(45) NOT NULL,
  `referencenumber` VARCHAR(45) NOT NULL,
  `invoicedate` DATE NOT NULL,
  `duedate` DATE NOT NULL,
  `bankaccountnumber` VARCHAR(30) NOT NULL,
  `amountexclvat` DECIMAL NOT NULL,
  `vat` DECIMAL NOT NULL,
  `totalamount` DECIMAL NOT NULL,
  `InvoiceStatus_id` INT NOT NULL,
  `comments` VARCHAR(100) NULL,
  PRIMARY KEY (`invoicenumber`),
  INDEX `fk_InvoiceHeader_InvoiceStatus1_idx` (`InvoiceStatus_id` ASC) VISIBLE,
  CONSTRAINT `fk_InvoiceHeader_InvoiceStatus1`
    FOREIGN KEY (`InvoiceStatus_id`)
    REFERENCES `rpacourse`.`InvoiceStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpacourse`.`InvoiceRow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpacourse`.`InvoiceRow` (
  `invoicenumber` INT NOT NULL,
  `rownumber` INT NOT NULL,
  `description` VARCHAR(100) NULL,
  `quantity` INT NULL,
  `unit` VARCHAR(45) NULL,
  `unitprice` DECIMAL NULL,
  `vatpercent` DECIMAL NOT NULL,
  `vat` DECIMAL NOT NULL,
  `total` DECIMAL NULL,
  PRIMARY KEY (`invoicenumber`, `rownumber`),
  CONSTRAINT `fk_invoicerow_InvoiceHeader`
    FOREIGN KEY (`invoicenumber`)
    REFERENCES `rpacourse`.`InvoiceHeader` (`invoicenumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
